### ISSUE TITLE
Cannot play podcast in Firefox

### ISSUE THREAD

**Issue by eatradish** [jessuni/shikwasa#18]
I tried using shikwasa on my blog and found that the podcast cannot be played under Firefox, but it works well on Edge (chromium), I tried on another website that uses shikwasa (https://buzaichang.xyz/episodes/four-women) tried it and found that the problem was also reproduced.

**Comment by jessuni** [comment]
Do you mean no sound output by 'cannot be played'? If so, it is reproducible in Firefox. Let me investigate the issue.

**Comment by eatradish** [comment]
cc
[2020-06-19 15-31-39.zip](https://github.com/jessuni/shikwasa/files/4803090/2020-06-19.15-31-39.zip)

**Comment by jessuni** [comment]
Thanks. Could you share a bit more about the Firefox version and Shikwasa config? Any error in console?

**Comment by eatradish** [comment]
Firefox version: 77.0.1 (64bit, Windows 10 2004)

shikwasa config:

```
<head>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/shikwasa@2.0.0/dist/shikwasa.min.css"></head>
<body>
<script src="https://cdn.jsdelivr.net/npm/shikwasa@2.0.0/dist/shikwasa.min.js"></script>
    <div class="element-of-your-choice">
        <!-- this is where the player will be injected -->
    </div>
    <script>
        const player = new Shikwasa({
            container: () => document.querySelector('.element-of-your-choice'),
            audio: {
                    title: 'Hello World!',
                    artist: 'Shikwasa FM',
                    cover: '/favicon.png',
                    src: '/mp3/1.mp3',
            },
        });
    </script>
</body>
```

**Comment by eatradish** [comment]
I seem to see some errors:

```
媒体资源 http://localhost:4000/mp3/1.mp3 无法被解码。 Podcast-test
媒体资源 http://localhost:4000/mp3/1.mp3 未能解码，错误：Error Code: NS_ERROR_DOM_MEDIA_MEDIASINK_ERR (0x806e000b)
Details: OnMediaSinkAudioError
```

**Comment by eatradish** [comment]
Can be reproduced at https://buzaichang.xyz/episodes/four-women :

```
媒体资源 https://r.typlog.com/eyJzIjo4NjgsImUiOjI0OTAsInAiOjIsInUiOiI…yMY0MbhUaXQs5My6DBbZiHAHro/buzaichang/8407868990_1283045.mp3 无法被解码。 four-women
媒体资源 https://r.typlog.com/eyJzIjo4NjgsImUiOjI0OTAsInAiOjIsInUiOiI…yMY0MbhUaXQs5My6DBbZiHAHro/buzaichang/8407868990_1283045.mp3 未能解码，错误：Error Code: NS_ERROR_DOM_MEDIA_MEDIASINK_ERR (0x806e000b)
Details: OnMediaSinkAudioError
```

**Comment by jessuni** [comment]
I tried Firefox 77.0.1 with Windows 10 with no problem, but there must be something wrong. It seems the audio file cannot be properly decoded. Can you remove Shikwasa completely from the code and add an HTML5 audio element with the same audio source?

Something like this:

```js
const audio = new Audio()
document.body.append(audio)
audio.src = '...'
```

**Comment by eatradish** [comment]
![图片](https://user-images.githubusercontent.com/19554922/85112432-33858800-b248-11ea-9436-c36b3a3f57f3.png)

It seems that setting "严格" to "标准" will solve the problem.

**Comment by jessuni** [comment]
In the case of [https://buzaichang.xyz/](https://buzaichang.xyz/episodes/four-women), the privacy restriction is probably caused by Cloudflare's cross-site track cookie, but still have no idea why Firefox would block a local media. Anyway, glad it's solved. Have fun playing with Shikwasa!
