### ISSUE TITLE
Cover not showing in Chrome mini-player

### ISSUE THREAD

**Issue by smilingpeanut** [jessuni/shikwasa#22]
Bug: when passing a cover image to the player, the cover does not show up in the Chrome mini-player. 

Example:
https://shikwasa.js.org/

Example of working cover:
https://www.noco.fm/podcasts/cdd584da-0ba6-49b4-b128-859ec32e4bef

**Comment by jessuni** [comment]
Thanks for the report. Will fix it in v2.0.1.
