### ISSUE TITLE
Iframe embed has no cover image displaying

### ISSUE THREAD

**Issue by Anil-matcha** [jessuni/shikwasa#27]
Hi @jessuni , 

I am trying to create an embed of the Shikwasa audio player and then use an iframe to play it on my website similar to how other podcast players work.

But I see an issue happening here, whenever I create an iframe of the page containing Shikwasa player, the cover is not being show. For example this is the normal webpage with only shikwasa player http://api.peervadoo.com/embed_audio . Then I have created a new page using iframe of the above webpage here http://api.peervadoo.com/test_embed_audio . 

As you can see, test_embed_audio has no cover image and some white space is added to top while the normal webpage version works fine. Can you kindly let me know what could be the issue here and if any workaround ?

**Comment by jessuni** [comment]
The UI is responsive. If you set a larger `width` for the iframe you'll see the cover photo. The UI without cover is designed for smaller screens, particularly mobile screens. If you need the player to maintain the large screen style, you'll have to write your own CSS I'm afraid.
