### ISSUE TITLE
Is it possiable to add chapter support ?

### ISSUE THREAD

**Issue by fqxufo** [jessuni/shikwasa#3]
Pocket casts supports chapter navigation while streaming podcast, so I think it's feasible.

**Comment by fqxufo** [comment]
Find a library [jsmediatags](https://github.com/aadsm/jsmediatags), it will parse id3 info from media file and seems supportting chapter metadata [](https://github.com/aadsm/jsmediatags/issues/42#issuecomment-310910996)

**Comment by jessuni** [comment]
@fqxufo Thanks for the suggestion! I was planning to write an API that allows seeking a certain time point of audio, since many podcasts also put a timeline in their show notes as navigation. This functions similarly to what you proposed, I'll look into it and see if I can include both.

**Comment by jessuni** [comment]
This feature is released under v2.0.0-beta.0. Closing the issue.
