### ISSUE TITLE
Marquee animation does not update on `updateMetadata`

### ISSUE THREAD

**Issue by jessuni** [jessuni/shikwasa#30]
Text scrolling animation does not update after `updateMetadata` is called.

**Comment by jessuni** [comment]
After a closer examination, it turns out that the animation does not update on `update` either. Will fix both.

**Comment by jessuni** [comment]
fixed in commit 560c291

**Comment by smilingpeanut** [comment]
@jessuni Can you tag v2.1.2? Thanks!

**Comment by jessuni** [comment]
@smilingpeanut done
