### ISSUE TITLE
Waveform animation in audio player

### ISSUE THREAD

**Issue by Anil-matcha** [jessuni/shikwasa#37]
Is it possible to add a waveform animation for the audio player similar to other popular podcasting players ? 

This would provide a great boost to the look of the player.

Thanks in advance.

**Comment by jessuni** [comment]
What kind of waveform are you looking for? Retrieving data from audio is possible through web audio API but not HTML5 audio, which is what this library uses.

**Comment by Anil-matcha** [comment]
@jessuni Thanks a lot for replying. What I was mentioning is a waveform like below on the audio player which is quite engaging to the listener. There are few libraries I see which can help with waveform like here https://github.com/katspaugh/wavesurfer.js/ . Wanted to check if we can integrate something like that into the audio player

![219194164_979258039596261_6361914477921910905_n](https://user-images.githubusercontent.com/4326215/126363683-65337a2a-bb98-4bf8-954f-d8a49e42858e.jpg)

**Comment by jessuni** [comment]
As a matter of fact, I have written several styles of waveform with Web Audio API and Shikwasa in the past: 
https://gist.github.com/jessuni/94120edb2b6d8442388b84fa5946c915 

The only difference is that the data I used is frequency byte, not the one used to generate the waveform in your screenshot. Although internally you'll have to handle the audio data completely by yourself, it's definitely achievable function-wise. You can make use of the plugin system as well.


FYI: If you're going to decode the audio data in front end, it has a huge cost, especially for podcasts. I have a [blog post](https://jessieji.com/2019/why-generating-waveform-for-a-large-audio-file-may-not-be-a-good-thing) that explains it.

**Comment by Anil-matcha** [comment]
@jessuni  Thanks a lot for sharing the information. Can you kindly share any documentation for creating a simple plugin to the audio player. I understand chapters is a plugin which is present but it has a lot of code specific to chapters so if there is a barebones example/documentation for building a simple plugin, it would be very helpful

**Comment by jessuni** [comment]
Sure. I haven't got time to organize and refine the details of the plugin API, so right now it's only used internally, does not support options and only have one hook. But all the audio events and player events are available to make up for the lack of hooks.

The plugin should be a class where it could later be registered to Shikwasa. Say a user instantiates the player with

```javascript
import Shikwasa from 'shikwasa'
import Plugin from '...'

Shikwasa.use(Plugin)
const player = new Shikwasa(options)
```
The registered plugin will then be instantiated when in the internal function `renderComponents`([code](https://github.com/jessuni/shikwasa/blob/7bbc3230721f920476f2ed9985721b5b694863e9/src/player.js#L406))

Then the plugin would have the structure like the following
```javascript
class Plugin {
  // `ctx` is the `player` instance
  constructor(ctx) {}
  
  // called before the player is being destroyed
  destroy() {}
}

// the name of the plugin would be used as the key in `player.comps`
Plugin._name = 'my-plugin-name'
```

**Comment by Anil-matcha** [comment]
Thanks a lot @jessuni for sharing the information. I am closing this thread now
