### ISSUE TITLE
Using loop in options to iterate and add chapters data

### ISSUE THREAD

**Issue by hayschan** [jessuni/shikwasa#42]
My function is declared as follow for my hexo podcast.  Shikwasa is fabulous.  Love the design.
```javascript
hexo.extend.tag.register('podplayer', function (args) {
    return `
    <div class="podcast"></div>\
    <script>\
        const player = new Shikwasa({
            container: () => document.querySelector('.podcast'),\
            audio: {\
                title: '${this.title}',\
                artist: '${this.author}',\
                cover: '${this.image}',\
                src: '${this.media}',\
            },\
            fixed: {\
                type: 'static',\
            },\
        });\
    </script>`
});
```

Then, I want to add my chapters options.  They are in a nested array of `${this.chapters}`, the data structure look like this:
```yaml
chapters:
  [
    ["00:00:00.000", "Title 1"],
    ["00:00:30.000", "Another title"]
  ]
```
I can access them by index, e.g. `${this.chapters[0][1]}` ,`${this.chapters[0][0]}` and `${this.chapters[1][0]}`, etc.  

By substituting the corresponding element with `title`, `startTime`, `endTime`.

```javascript
chapters: [
      { title, startTime, endTime }, // the first chapter
      { title, startTime, endTime }, // the second chatper
],
```

I get something like this ⬇️
```javascript
chapters: [
  { ${this.chapters[0][1]}, ${this.chapters[0][0]}, ${this.chapters[1][0]} }, // the first chapter
  { ${this.chapters[1][1]}, ${this.chapters[1][0]}, ${this.chapters[2][0]} }, // the second chapter
{ ${this.chapters[1][1]}, ${this.chapters[1][0]}, ${this.chapters[2][0]} }, // the second chatper
  { title, startTime, endTime }, // the third chatper
],
```

Is there a way I can use a `for loop` to iterate my chapters? **So that one line of code would be able to generate all my chapters automatically.**

```javascript
chapters: [
   { ${this.chapters[i][1]}, ${this.chapters[i][0]}, ${this.chapters[i+1][0]} }, // i to n chapter
],
```

I've tried using `<% %>` tags but have no luck.

```javascript
<script type="text/javascript">
    <% ${this.chapters}.forEach(function(row) { %>
        console.log("<%= row[1] %>, <%= row[0] %>"); // or anything you want to do.    
    <% }) %>
</script>
```

It would just output my loop code.

![image-20211214022927603](https://cdn.jsdelivr.net/gh/hayschan/oss@master/2021/12/14/image-20211214022927603.png)

Is this even possible? Any tips or hints will be appreciated.  Thx.

**Comment by jessuni** [comment]
Thanks for using Shikwasa. This issue has more to do with Hexo templating language providing an iteration function for you to reorganize the array. I'm not familiar with Hexo, but here's some info I found that might help.

https://hexo.io/api/generator#Generate-All-Posts
https://github.com/hexojs/hexo/issues?q=iterate

You could also check Hexo's plugins or ask for help in their community.
