### ISSUE TITLE
Hiding/obscuring audio file from Network tab in Developer Tools?

### ISSUE THREAD

**Issue by youssefavx** [jessuni/shikwasa#43]
Hey! 

Thank you for making this incredible player. I've been searching for one that hides the file from the DOM and this one served that purpose but now I'm curious if it might be possible to also hide or obscure the file from the Network tab. I've seen a lot of people saying that this is basically impossible, however, I've also seen people seemingly falsifying that hypothesis: https://preventdirectaccess.com/extensions/protect-wordpress-videos/

Try opening the network tab, then playing that video. You'll see a link to a .ts video. If you try opening it won't play, nor download the video - rather a file with that name. 

If the video keeps playing you see it seems to be pieces of the video that are being streamed. 

1. I wonder how they're doing that...
2. I wonder if I could do something similar with shikwasa? 

Or rather just preventing direct access to the file, such that if the user opens the direct link, they're redirected to the page with the player.

**Comment by jessuni** [comment]
Thanks for using Shikwasa. However, I'm afraid hiding the audio source request from the network inspector is not the primary focus of this library. What this player does, is to offer a friendly GUI to users and no more. It does not interfere with requests.

If you're interested in what you proposed, you could always experiment without Shikwasa :)
