### ISSUE TITLE
Cannot redefine chapters when creating a second player

### ISSUE THREAD

**Issue by editpetercolquhoun** [jessuni/shikwasa#55]
When I create the first player everything works fine but trying to create a second player causes an error `TypeError: Cannot redefine property: chapters` this stops a second player from being created.
Full stack trace
`
Uncaught TypeError: Cannot redefine property: chapters
    at Function.defineProperties (<anonymous>)
    at Chapter.patchPlayer (bundle.js:102149:12)
    at Chapter.init (bundle.js:102092:10)
    at bundle.js:102103:14
    at bundle.js:103025:39
    at Array.forEach (<anonymous>)
    at Events.trigger (bundle.js:103025:25)
    at Player.update (bundle.js:103421:19)
    at Player.initAudio (bundle.js:103244:12)
    at new Player (bundle.js:103082:10)
`

An example of how I am creating the player, this is triggered by button press when a user needs to create a player.
```js
const chapters = [
      { title: 'First Chapter', startTime: 0, endTime: 2 },
      { title: 'Second Chapter', startTime: 2, endTime: 4 },
]


Shikwasa.use(Chapter)
      const player = new Shikwasa({
        container: () => document.querySelector('#e' + widgetID),
        audio: {
          title: titleTmp,
          artist: artist,
          cover: require('./testPic.jpeg'),
          src: require('./testFile.mov'),
          Chapter: chapters
        },
        theme: theme,
        themeColor: themeColour,
      })
```
I've checked all the variables exist and so do the test files. Thanks

**Comment by editpetercolquhoun** [comment]
Also is it possible to stop the player from moving to the bottom of the screen when the screen is too small?

**Comment by jessuni** [comment]
Did you register the plugin twice? The plugin is registered once, applied to every instance.
There's also an error in your snippet, it should be `chapters` instead of `Chapter: chapters`

I include [a working fiddle here](https://jsfiddle.net/jessuni/pas6rL2u/) with two players powered by the chapter plugin for you to check and debug.
