### ISSUE TITLE
inviting to Musicoin

### ISSUE THREAD

**Issue by immartian** [jessuni/shikwasa#6]
Good job with the player. @jessuni 
I'd love to invite you to Musicoin Project at https://musicoin.org to join an experiment project at pod.musicoin.org (upcoming), to jointly develop a podcasting community. 

join our slack https://join.slack.com/t/musicoin/shared_invite/enQtNzEyODU1NjkyMDk2LWNjZjY4OTY5ZWIxNzllZWZjYThkYTMyYzdiMTBlODQwYzdhOWJkZTI3MWY4OTZkODVkNDZmOGUyMmRmOTE4ODA if you are interested.

**Comment by jessuni** [comment]
Joined!
