### ISSUE TITLE
Seek control

### ISSUE THREAD

**Issue by smkhtkn** [jessuni/shikwasa#68]
Hello. Please excuse me, but I'm quite new to JavaScript.

I made my first player Shikwasa for the Survivor Memories website. However, I have absolutely no idea how I can add timecodes.

For example, how can I add the timecode **"05:06 She talks about herself"?**

https://codepen.io/andriy-smkhtkn/pen/PoezOQr

I don't know how to use that:

```
anchor.addEventListener('click', (e) => {
    const href = e.target.getAttribute('href')
    const time = formatTime(href)
    instance.seek(time)
    instance.play()
  })
```

Excuse me again!

Have a good day.

**Comment by jessuni** [comment]
I created a working example based on your snippet [here](https://codepen.io/jessieonfire/pen/KKexNQy?editors=1111). Comments are added inline to help you understand better.
Hope it helps and have fun with Shikwasa!

**Comment by smkhtkn** [comment]
Thank you very much for your responsiveness! 

Your example helped me a lot.

Shikwasa is the best player!
