### ISSUE TITLE
Weird layout in my react project

### ISSUE THREAD

**Issue by ChenReason** [jessuni/shikwasa#7]
![image](https://user-images.githubusercontent.com/5564388/62607239-54930200-b930-11e9-9fd0-ea381312056e.png)

import React, { Component } from 'react';
import Shikwasa from 'shikwasa';

export default class TestPage extends Component {
  constructor(props) {
    super(props);
    this.myRef = React.createRef();
  }
  componentDidMount() {
    let player = new Shikwasa({
      fixed: {
        type: 'auto',
        position: 'bottom',
      },
      container: this.myRef.current,
      transitionSpeed: 3,
      themeColor: '#00869B',
      autoPlay: false,
      muted: false,
      preload: 'metadata',
      speedOptions: [0.5, 0.75, 1.25, 1.5],
      audio: {
        title: 'Hello World!',
        artist: 'Shikwasa FM',
        src: 'http://www.music.helsinki.fi/tmt/opetus/uusmedia/esim/a2002011001-e02-128k.mp3',
      },
    })
  }

  render() {
    return (
      <div>
        <div ref={this.myRef}></div>
      </div>
    )
  }
}

**Comment by jessuni** [comment]
You need to import stylesheet as well. Sorry I didn't mention it in the documentation, README has been updated to include this info. 
The path of css file is `shikwasa/dist/shikwasa.min.css`
